### ISSUE TITLE
Wikivoyage wrong page banner img

### ISSUE THREAD

**Issue by orionseye** [maxlath/hub#20]
Today i discovered a problem, where wikivoyage requested banner is not returned as expected.
https://en.wikivoyage.org/wiki/Berlin/Mitte
https://tools.wmflabs.org/hub/enwikivoyage:Berlin/Mitte?property=P948&width=450 
gives me a wrong image

while others, with forward slash, work fine, e.g.
https://tools.wmflabs.org/hub/enwikivoyage:Tokyo/Shinjuku?property=P948&width=450

**Comment by maxlath** [comment]
I get the following
```
GET https://tools.wmflabs.org/hub/enwikivoyage:Berlin/Mitte?property=P948&width=450
=> 308 https://hub.toolforge.org/enwikivoyage:Berlin/Mitte?property=P948&width=450
=> 302 https://commons.wikimedia.org/wiki/Special:FilePath/Memorial_Murdered_Jews_of_Europe_banner.jpg?width=450
=> 302 https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Memorial_Murdered_Jews_of_Europe_banner.jpg&width=450
=> 301 https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Memorial_Murdered_Jews_of_Europe_banner.jpg/450px-Memorial_Murdered_Jews_of_Europe_banner.jpg
```
This last URL seems to be desired outcome, no?

**Comment by orionseye** [comment]
No, the desired outcome should be this image
https://upload.wikimedia.org/wikipedia/commons/5/53/Berlin_Mitte_Wikivoyage_Banner_2.png

**Comment by maxlath** [comment]
The data source for the hub isn't the wiki themselves (in this case enwikivoyage) but Wikidata, and on Wikidata, the page banner property of [Berlin-Mitte (Q2013767)](https://www.wikidata.org/wiki/Q2013767#P948) has been set to https://commons.wikimedia.org/wiki/File:Memorial_Murdered_Jews_of_Europe_banner.jpg since [a bot edit in 2013](https://www.wikidata.org/w/index.php?title=Q2013767&oldid=77172200). You are very welcome to correct it there, but it's not a bug from the hub point of view
